# Generated by Django 3.2.9 on 2021-12-05 13:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='full_name',
            field=models.CharField(default=datetime.datetime(2021, 12, 5, 13, 38, 56, 2083, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
